radarr:
  tyzen9-radarr:
    base_url: http://hostname:7878
    api_key: << YOUR API KEY >>

    # Quality Definitions: https://recyclarr.dev/reference/configuration/quality-definition/
    quality_definition:
      type: movie
      preferred_ratio: 0.5
      qualities:
        # Max and preferred values in Radarr's quality definitions represent MB per minute
        # of runtime limits, not total file size. Radarr multiplies these by estimated movie
        # length to calculate actual rejection/grab thresholds
        #
        # Actual File Size Limit = (max/preferred value) × runtime_minutes
        #     We will assume a 150min (2.5h) movie for these calculations
        - name: Bluray-2160p
          max: 150              # 150 MB/min × 150min (2.5hr movie) = 22GB
          min: 82.6             # 12.5GB  (TRaSH DEFAULT: 82.6)
          preferred: 100        # 15GB
        - name: WEBDL-2160p
          max: 150              # 22GB
          min: 25               # 3.7GB   (TRaSH DEFAULT: 25)
          preferred: 100        # 15GB
        - name: WEBRip-2160p
          max: 150              # 22GB
          min: 25               # 3.7GB   (TRaSH DEFAULT: 25)
          preferred: 100        # 15GB
        - name: WEBDL-1080p
          max: 100              # 15GB
          min: 12.5             # 1.9GB   (TRaSH DEFAULT: 12.5)
          preferred: 50         # 7.5GB
        - name: WEBRip-1080p
          max: 100              # 15GB
          min: 12.5             # 1.9GB   (TRaSH DEFAULT: 12.5)
          preferred: 50         # 7.5GB
        - name: WEBDL-720p
          max: 80               # 12GB
          min: 8                # 1.2GB   (TRaSH DEFAULT: 8)
          preferred: 20         # 3GB
        - name: WEBRip-720p
          max: 80               # 12GB
          min: 8                # 1.2GB   (TRaSH DEFAULT: 8)
          preferred: 20         # 3GB

    quality_profiles:
      # ------------------------------------------------------------------------
      - name: HD 1080p                   # Exact name that will appear in Radarr
        upgrade:
          allowed: true                  # Enable upgrades
          until_quality: WEB 1080p       # Stop upgrading once this is reached
          until_score: 10000             # Upgrade Until Custom Format Score
        min_format_score: 0              # Minimum Custom Format Score
        min_upgrade_format_score: 1      # Minimum Custom Format Score Increment
        qualities:
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
          - name: WEB 720P
            qualities:
              - WEBRip-720p
              - WEBDL-720p
      # ------------------------------------------------------------------------
      - name: 4K 2160p                   # Exact name that will appear in Radarr
        upgrade:
          allowed: true                  # Enable upgrades
          until_quality: WEB 2160p       # Stop upgrading once this is reached
          until_score: 10000             # Upgrade Until Custom Format Score
        min_format_score: 0              # Minimum Custom Format Score
        min_upgrade_format_score: 1      # Minimum Custom Format Score Increment
        qualities:
          - name: Bluray-2160p
          - name: WEB 2160P
            qualities:
              - WEBRip-2160p
              - WEBDL-2160p
          - name: WEB 1080P
            qualities:
              - WEBRip-1080p
              - WEBDL-1080p
          - name: WEB 720P
            qualities:
              - WEBRip-720p
              - WEBDL-720p

    delete_old_custom_formats: true        # Prefer a full refresh of CFs
    replace_existing_custom_formats: true  # Prefer a full refresh of CFs
    custom_formats:
      - trash_ids:
          # ----------------------------------------------------------------------
          # This list comes from the command: recyclarr list custom-formats radarr
          # ----------------------------------------------------------------------
          # HQ Release Groups
          - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
          - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
          - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
          - 4d74ac4c4db0b64bff6ce0cffef99bf0 # UHD Bluray Tier 01
          - a58f517a70193f8e578056642178419d # UHD Bluray Tier 02
          - e71939fae578037e7aed3ee219bbe7c1 # UHD Bluray Tier 03
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03
          # General Streaming Services
          - b3b3a6ac74ecbd56bcdbefa4799fb9df # AMZN
          - df13ed57843877b21ad969184ab6888f # ATV
          - 40e9380490e748672c2522eaaeb692f7 # ATVP
          - cc5e51a9e85a6296ceefe097a77f12f4 # BCORE
          - 16622a6911d1ab5d5b8b713d5b0036d4 # CRiT
          - 84272245b2988854bfb76a16e60baea5 # DSNP
          - 509e5f41146e278f9eab1ddaceb34515 # HBO
          - 5763d1b0ce84aff3b21038eea8e9b8ad # HMAX
          - 526d445d4c16214309f0fd2b3be18a89 # Hulu
          - 2a6039655313bf5dab1e43523b62c374 # MA
          - 6a061313d22e51e0f25b7cd4dc065233 # MAX
          - 170b1d363bd8516fbf3a3eb05d4faff6 # NF
          - c9fd353f8f5f1baf56dc601c4cb29920 # PCOK
          - 350e9170619683a55cb9191d0b1ababa # PLAY
          - e36a0ba1bc902b26ee40818a1d59b8bd # PMTP
          - 44c2b54d7c81c1a442a8b2cabeaef54f # ROKU
          - c2863d2a50c9acad1fb50e53ece60817 # STAN
          - e0ec9672be6cac914ffad34a6b077209 # iT
          # Miscellaneous
          - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
          - ae43b294509409a6a13919dedd4764c4 # Repack2
          - 5caaaa1c08c1742aa4342d8c4cc463f2 # Repack3
          # Unwanted
          - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
          - cae4ca30163749b891686f95532519bd # AV1
          - ed38b889b31be83fda192888e2286d83 # BR-DISK
          - 0a3f082873eb454bde444150b70253cc # Extras
          - e6886871085226c3da1830830146846c # Generated Dynamic HDR
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
          - e204b80c87be9497a8a6eaff48f72905 # LQ (Release Title)
          - 712d74cd88bceb883ee32f773656b1f5 # Sing-Along Versions
          - bfd8eb01832d646a0a89c4deb46f8564 # Upscaled
          - dc98083864ea246d05a42df0d05f81cc # x265 (HD)

        assign_scores_to:
          - name: HD 1080p  # Your exact custom profile name
          - name: 4K 2160p  # Your exact custom profile name