###################################################################################################
# Recyclarr Configuration Template: WEB-1080p (V4)                                                #
# Updated: 2024-10-02                                                                             #
# Documentation: https://recyclarr.dev                                                            #
# Note: If you are using multiple profiles in a single instance, please read the following        #
# documentation about file merging:                                                               #
# https://recyclarr.dev/reference/config-examples/#merge-single-instance                          #
# This config file is for use with Sonarr V4 only                                                 #
###################################################################################################

# Instance Definition: https://recyclarr.dev/reference/configuration/basic/
sonarr:
  web-1080p-v4:
    base_url: http://127.0.0.1:8989 
    api_key: fbfe0d61eee349be86991afc3bf8bb8e

    include:
      # We will override quality definitions below
      # - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p

    # Quality Definitions: https://recyclarr.dev/reference/configuration/quality-definition/
    quality_definition:                                                                     
      type: series                                                                         
      preferred_ratio: 0.5                                                                
      qualities: 
        - name: WEBDL-1080p                                                                  
          max: 100           # ~5GB for 42min; adjust down (e.g., 100 for ~4GB) if too big   
          preferred: 80      # Aims for ~3.3GB/episode                                       
        - name: WEBRip-1080p
          max: 100
          preferred: 80
        - name: Bluray-1080p # If enabled in profile...limit to avoid huge remuxes           
          max: 100    
          preferred: 80
        - name: WEBDL-720p
          max: 80
          preferred: 50
        - name: WEBRip-720p
          max: 80
          preferred: 50

    # Custom Formats: https://recyclarr.dev/reference/configuration/custom-formats/
    custom_formats:
      # Optional
      - trash_ids:
          # - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          # - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          # - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          # - 06d66ab109d4d2eddb2794d21526d140 # Retags
          # - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-1080p

      - trash_ids:
          # Uncomment the next six lines to allow x265 HD releases with HDR/DV
          # - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        # assign_scores_to:
          # - name: WEB-1080p
            # score: 0
      # - trash_ids:
          # - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
          - name: WEB-1080p
